name: CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Stop existing PM2 process
      run: pm2 stop test-deployment || true

    - name: Delete existing PM2 process
      run: pm2 delete test-deployment || true

    - name: Start application with PM2
      run: pm2 start npm --name "test-deployment" -- start

    - name: Save PM2 configuration
      run: pm2 save

    - name: Show PM2 status
      run: pm2 list