name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /home/bilaltoor/test-deployment  # Replace with actual path

    steps:
    - name: Pull latest code
      run: git pull origin main

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Stop existing PM2 process
      run: pm2 stop next-app || true

    - name: Delete existing PM2 process
      run: pm2 delete next-app || true

    - name: Start application with PM2
      run: pm2 start npm --name "next-app" -- start

    - name: Save PM2 configuration
      run: pm2 save
